[package]
name = "shamir_secret_sharing"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "shamir_secret_sharing"
path = "src/main.rs"

[lib]
name = "shamir_secret_sharing"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.5"
winter-math = "0.4.0"
winterfell = "0.4.0"
fernet = "0.1.4"
base64 = "0.13.0"