[package]
name = "shamir_secret_sharing"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "shamir_secret_sharing"
path = "src/main.rs"

[lib]
name = "shamir_secret_sharing"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.5"
bacon-sci="0.13.1"